### ISSUE TITLE
Error: Invalid src prop on next/image - hostname not configured in next.config.js

### ISSUE THREAD

**Issue by mukles-dev** [einfoengine/trouthsocial#1]
I encountered an error while using the next/image component with an external URL. The error occurs when trying to load an image from https://place-hold.it/300x500. The error message suggests that the hostname "place-hold.it" is not configured under images in next.config.js.

**Comment by mukles** [comment]
Make sure to change the configuration from `next.config.cjs` to `next.config.js` and use the following configuration to resolve the issue:

```js
/** @type {import('next').NextConfig} */

const path = require("path");

module.exports = {
  sassOptions: {
    includePaths: [path.join(__dirname, "styles")],
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "place-hold.it",
        port: "",
        pathname: "/**",
      },
    ],
  },
};


```

**Comment by einfoengine** [comment]
Still, it's not working! The only solution I am using temporarily is the 'unoptimized' property with the Image component.

**Comment by mukles** [comment]
To resolve the issue, follow these steps:

1. **Rename the Configuration File**: Rename your `next.config.cjs` file to `next.config.js`.

2. **Apply the Configuration**: Copy and use the configuration you provided earlier in the renamed file (`next.config.js`).

3. **Delete the `.next` Folder**: After making these changes, delete the `.next` folder to clear any cached data and ensure the configuration is applied correctly.

Following these steps should help fix the issue you're facing.

**Comment by einfoengine** [comment]
Thanks, and working perfectly :)
